### ISSUE TITLE
Cannot launch "Start Bot.bat"

### ISSUE THREAD

**Issue by KryvasCZ** [Aaronidk/hentaibot#2]
so i installed everything nodejs,"install.bat" and i checked if everything was right like bot id and user id and it was but still my bot is not launching i attached image w my installs and setup stuff

![bot token](https://user-images.githubusercontent.com/57132342/67753405-f0667280-fa34-11e9-91ef-611abfa300ec.PNG)

![client ID](https://user-images.githubusercontent.com/57132342/67753413-f3616300-fa34-11e9-8e31-4ca2a5dbd306.PNG)

![all installed](https://user-images.githubusercontent.com/57132342/67753240-b9905c80-fa34-11e9-98bf-7f3df087d989.PNG)

**Comment by Aaronidk** [comment]
when u clicked start.bat what output did the console give.

**Comment by KryvasCZ** [comment]
it didnt give me any output it just flashed cmd for a sec and then the cmd disappeared

**Comment by KryvasCZ** [comment]
btw sry for late reply

**Comment by Aaronidk** [comment]
did you click install.bat before oppening the start.bat sometimes if the npm modules arent installed it will just crash. If you want personal help contact my discord. Aaron#7444

**Comment by KryvasCZ** [comment]
so i sent you friend request on discord my name is same as here
